trigger:
- master

schedules:
- cron: "0 0 * * 1"
  displayName: Weekly Build
  branches:
    include:
    - master
  always: true

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

- stage: 'Build'
  displayName: 'Build & Push Images'

  jobs:  

  - job: 'Build_JDK_11'
    displayName: 'Build JDK 11'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build JDK 11 Image'
      inputs:
        containerRegistry: 'Duchessa DockerHub'
        repository: 'duchessa/el8-jdk'
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          11.$(tag)
          11
    - task: Docker@2
      displayName: 'Push JDK 11 Image'
      condition: ne(Build.Reason, 'PullRequest')
      inputs:
        containerRegistry: 'Duchessa DockerHub'
        repository: 'duchessa/el8-jdk'
        command: 'push'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          11.$(tag)
          11
 
  - job: 'Build_JDK_8'
    displayName: 'Build JDK 8'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Build JDK 8 Image'
        inputs:
          containerRegistry: 'Duchessa DockerHub'
          repository: 'duchessa/el8-jdk'
          command: 'build'
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          arguments: '--build-arg JDK_VERSION=8'
          tags: |
            8.$(tag)
            8
      - task: Docker@2
        displayName: 'Push JDK 8 Image'
        condition: ne(Build.Reason, 'PullRequest')
        inputs:
          containerRegistry: 'Duchessa DockerHub'
          repository: 'duchessa/el8-jdk'
          command: 'push'
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: |
            8.$(tag)
            8
